# Generated by Django 4.0.1 on 2022-01-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='bhk',
            field=models.CharField(choices=[('1', 'One BHK'), ('1.5', '1.5 BHK'), ('2', 'Two BHK'), ('3', 'Three BHK'), ('4', 'Four BHK')], max_length=5),
        ),
    ]
