# Generated by Django 4.0.1 on 2022-02-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('society', '0002_alter_flat_bhk'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='society.flat'),
        ),
    ]
